/**
 * Community package publisher.
 *
 * Exports a package definition as a portable artifact (JSON + README).
 * No catalog dependency — reads from the PackageRegistry.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { getCommunityPackageRegistry } from './runtime';

export type PublishedPackageArtifact = {
  packageId: string;
  artifactPath: string;
  publishedAt: number;
};

export function packageSlug(packageId: string): string {
  return packageId.replace(/[^a-zA-Z0-9._-]+/g, '-');
}

/**
 * Export a package definition as a portable artifact (JSON + README).
 *
 * The route is the trust boundary: `projectRoot` is host-derived (never
 * caller-supplied) and the `packageId` must already be in this project's scope
 * — this function trusts neither. It only resolves the registry definition and
 * writes under the provided root.
 */
export function publishPackage(packageId: string, projectRoot: string): PublishedPackageArtifact {
  const id = packageId.trim();
  if (!id) {
    throw new Error('packageId is required');
  }

  const definition = getCommunityPackageRegistry().getPackage(id);
  if (!definition) {
    throw new Error(`Package not found: ${id}`);
  }

  const baseDir = join(projectRoot, 'publish', packageSlug(id));
  mkdirSync(baseDir, { recursive: true });

  const artifactPath = join(baseDir, 'package.json');
  writeFileSync(artifactPath, JSON.stringify(definition, null, 2), 'utf-8');

  writeFileSync(
    join(baseDir, 'README.md'),
    [
      `# ${definition.name}`,
      '',
      `Package ID: \`${definition.id}\``,
      '',
      'This artifact was generated by the community package publisher.',
      'Import target: `package.json#neuralis` or serialized PackageDefinition JSON',
    ].join('\n'),
    'utf-8',
  );

  return {
    packageId: id,
    artifactPath,
    publishedAt: Date.now(),
  };
}
